export const alunos = [
    {
      nome: "Ana Silva",
      idade: 20,
      foto: "https://mockmind-api.uifaces.co/content/human/217.jpg",
      notas: [
        { materia: "Matemática", nota: 85 },
        { materia: "Português", nota: 90 },
        { materia: "História", nota: 78 },
        { materia: "Geografia", nota: 88 },
        { materia: "Ciências", nota: 92 },
        { materia: "Inglês", nota: 80 },
      ],
    },
    {
      nome: "Bruno Souza",
      idade: 22,
      foto: "https://mockmind-api.uifaces.co/content/human/218.jpg",
      notas: [
        { materia: "Matemática", nota: 75 },
        { materia: "Português", nota: 80 },
        { materia: "História", nota: 70 },
        { materia: "Geografia", nota: 85 },
        { materia: "Ciências", nota: 78 },
        { materia: "Inglês", nota: 82 },
      ],
    },
    {
      nome: "Carla Pereira",
      idade: 19,
      foto: "https://mockmind-api.uifaces.co/content/human/219.jpg",
      notas: [
        { materia: "Matemática", nota: 95 },
        { materia: "Português", nota: 88 },
        { materia: "História", nota: 92 },
        { materia: "Geografia", nota: 90 },
        { materia: "Ciências", nota: 94 },
        { materia: "Inglês", nota: 89 },
      ],
    },
    {
      nome: "Daniel Oliveira",
      idade: 21,
      foto: "https://mockmind-api.uifaces.co/content/human/222.jpg",
      notas: [
        { materia: "Matemática", nota: 65 },
        { materia: "Português", nota: 70 },
        { materia: "História", nota: 68 },
        { materia: "Geografia", nota: 72 },
        { materia: "Ciências", nota: 75 },
        { materia: "Inglês", nota: 78 },
      ],
    },
    {
      nome: "Eduarda Lima",
      idade: 20,
      foto: "https://mockmind-api.uifaces.co/content/human/220.jpg",
      notas: [
        { materia: "Matemática", nota: 88 },
        { materia: "Português", nota: 92 },
        { materia: "História", nota: 85 },
        { materia: "Geografia", nota: 90 },
        { materia: "Ciências", nota: 87 },
        { materia: "Inglês", nota: 91 },
      ],
    },
    {
      nome: "Alessandro B Vitorio",
      idade: 44,
      foto:"https://avatars.githubusercontent.com/u/221563114?v=4",
      notas: [
        { materia: "Matemática", nota: 100 },
        { materia: "Português", nota: 100 },
        { materia: "História", nota: 100 },
        { materia: "Geografia", nota: 100 },
        { materia: "Ciências", nota: 100 },
        { materia: "Inglês", nota: 100 },
      ],
    },
    {
      nome: "Felipe Costa",
      idade: 23,
      foto: "https://mockmind-api.uifaces.co/content/human/80.jpg",
      notas: [
        { materia: "Matemática", nota: 78 },
        { materia: "Português", nota: 75 },
        { materia: "História", nota: 80 },
        { materia: "Geografia", nota: 82 },
        { materia: "Ciências", nota: 77 },
        { materia: "Inglês", nota: 79 },
      ],
    },
    {
      nome: "Gabriela Fernandes",
      idade: 19,
      foto: "https://mockmind-api.uifaces.co/content/human/125.jpg",
      notas: [
        { materia: "Matemática", nota: 92 },
        { materia: "Português", nota: 95 },
        { materia: "História", nota: 90 },
        { materia: "Geografia", nota: 93 },
        { materia: "Ciências", nota: 94 },
        { materia: "Inglês", nota: 96 },
      ],
    },
    {
      nome: "Hugo Martins",
      foto: "https://mockmind-api.uifaces.co/content/human/201.jpg",
      idade: 21,
      notas: [
        { materia: "Matemática", nota: 68 },
        { materia: "Português", nota: 72 },
        { materia: "História", nota: 70 },
        { materia: "Geografia", nota: 75 },
        { materia: "Ciências", nota: 73 },
        { materia: "Inglês", nota: 71 },
      ],
    },
    {
      nome: "Isabela Rocha",
      idade: 20,
      foto: "https://mockmind-api.uifaces.co/content/human/216.jpg",
      notas: [
        { materia: "Matemática", nota: 89 },
        { materia: "Português", nota: 91 },
        { materia: "História", nota: 87 },
        { materia: "Geografia", nota: 90 },
        { materia: "Ciências", nota: 88 },
        { materia: "Inglês", nota: 92 },
      ],
    },
    {
      nome: "João Almeida",
      idade: 22,
      foto: "https://mockmind-api.uifaces.co/content/human/200.jpg",
      notas: [
        { materia: "Matemática", nota: 74 },
        { materia: "Português", nota: 78 },
        { materia: "História", nota: 76 },
        { materia: "Geografia", nota: 80 },
        { materia: "Ciências", nota: 79 },
        { materia: "Inglês", nota: 77 },
      ],
    },
  ];